### ISSUE TITLE
Enable grpc based clients 

### ISSUE THREAD

**Issue by g41797** [staticbackendhq/core#103]
just to discuss - support of grpc(grpc-web) on the server side will simplify development of client libraries
and gRPC is amazing buzzword now

**Comment by dstpierre** [comment]
Yes, but I'm not sure about the efforts required to support grpc in parallel of the REST API.

This certainly could help with client libraries generation. This need some investigation to measure the amount of work it would require to implement.

**Comment by dstpierre** [comment]
After giving this some thoughts, I don't think adding gRPC at this point would make things easier from the PoV of a user of StaticBackend.

It would help for client-side code generation, but the backend JSON API is already big enough to maintain without adding another layer.

Thanks for the suggestion.
