### ISSUE TITLE
token creation datetime not saving correctly in database

### ISSUE THREAD

**Issue by c-nv-s** [staticbackendhq/core#106]
**Describe the bug**
datetime of the creation of tokens are not being saved properly.
if I check in postgres by running:
```
select * from app_b28a9ba3_ef26_4672_ae5b_c248206517e2.sb_tokens ;
id | 7378efd1-3ef4-457f-96ab-adab4b22d727
account_id | f271bafa-6635-40ed-90ea-0ffb13b274b7
token | 9afe5b83-a093-441d-8e9c-55f971def713
email | hulk@hogan.com
password | $2a$10$FkqiT1A48Bjv7XavdDl1ge8W0mQwV......
role | 100
reset_code |
created | 0001-01-01 00:00:00
```
the ``created`` time is always saved as ``0001-01-01 00:00:00`` and not the actual time on the machine

**Comment by dstpierre** [comment]
good catch @c-nv-s - I'll fix this, and make sure other database provider are not having same bug.
