### ISSUE TITLE
Problem when i try run docker build command

### ISSUE THREAD

**Issue by dijalmasilva** [staticbackendhq/core#33]
**Describe the bug**
Problem to build the project using Docker on machine using Windows with WSL 2.

**To Reproduce**
Using the machine running Windows using Docker with WSL 2 ( with Ubuntu ).
    
- Clone the project.
- Copy .demo.env to .env
- Execute the docker build command: `docker build . -t staticbackend:latest`
- See the error

![image](https://user-images.githubusercontent.com/11358368/178407487-933431ee-55d0-4aea-8a04-cd72033d1a21.png)

**Comment by dijalmasilva** [comment]
Worked for me, changing the Go version to 1.18 on Dockerfile.

**Comment by dstpierre** [comment]
@dijalmasilva good catch. Thanks for confirming, I'll update the Dockerfile.
