### ISSUE TITLE
Fix TestHtmlToPDF occasional issue

### ISSUE THREAD

**Issue by dstpierre** [staticbackendhq/core#38]
**Describe the bug**
GitHub actions sometimes failed due to this test sometimes raising an error. I've seen it happened once in development as well.

> error line:128: context deadline exceeded

Lines in question:

```go
if resp.StatusCode > 299 {
  b, err := io.ReadAll(resp.Body)
  if err != nil {
    t.Fatal(err)
  }
  t.Log(string(b))
  t.Errorf("expected status 200 got %s", resp.Status)
}
```

**To Reproduce**
1. First remove the `t.Skip` in this test in `extras_test.go` line: 116
2. Running this test multiple times in a row should trigger the issue:

```bash
$ make thistest TestHtmlToPDF
```

**Expected behavior**
This should always work and not trigger this error

**Output of staticbackend -v**
This flag isn't implement yet.

**Comment by cmstoddard** [comment]
I would be willing to take this on.

**Comment by Charlton-A** [comment]
Hi @dstpierre I took a look and this and managed to reproduce the error by adding `--count 50`  to the test and making the errors  slightly  verbose. It occurs when the context times out on `chromedp.Run`  in  `htmlToX` func. 

> extras_test.go:135: chome dp context deadline exceeded

The docs for `chromedp.Run` also state that `Note that the first time Run is called on a context, a browser will be allocated via Allocator. Thus, it's generally a bad idea to use a context timeout on the first Run call, as it will stop the entire browser.` 

Possible solutions  to this would be:
1. Increasing context timeout period though this would not work cases where conversion to the respective formats take longer
2. Using contex without  timeout 

You can assign this to me and also let me know your thoughts on the above approaches.

**Comment by dstpierre** [comment]
@Charlton-A thanks, nice diagnostic.

Ok, seems like the timeout wasn't a good idea after all.

In that case, yes please remove that work-around and worst case the `go test` default timeout will kick in if something is wrong with the initialization of chrome.
