### ISSUE TITLE
Expose an HTTP client to the function runtime

### ISSUE THREAD

**Issue by dstpierre** [staticbackendhq/core#43]
The server-side functions run inside a custom JavaScript runtime. It only support bare JavaScript and has additional functionalities added via the VM.

One useful function would be to expose a way to perform HTTP requests from the function.

See `function/runtime.go` line:110.

Adding a helper function like `fetch` to keep "consistent" with the JS eco-system. Or something like `webreq`

I can see the function taking the following as parameters:

```javascript
// example from the function code PoV
const resp = webreq("POST", "https://myurl.com", {hello: "world"}, {"MY-HEADER-KEY": "something"});
```

This would accept the HTTP Method, URL, Body as JSON, Header as a map.

And this helper function would return:

```go
type HTTPResponse struct {
  Status int `json:"status"
  Body string `json:"body"
}
```

**Comment by ksankeerth** [comment]
Hi @dstpierre, 
I'm new to staticbackendhq. I'm interested in taking this issue. Could You please assign me? Thanks

**Comment by dstpierre** [comment]
Hey @ksankeerth welcome aboard :wave: 

If you haven't already, feel free to [join on Discord](https://discord.gg/vgh2PTp9ZB) as well.

Let me know if you have any questions or need to clarify anything in here.

Thank you for wanting to contribute to SB :100:

**Comment by ksankeerth** [comment]
Thanks for assigning me. I'll go through contribution guides and code. After the analysis, I'll discuss about the implementation.
