### ISSUE TITLE
Expose the Volatilizer interface functions to the server-side runtime

### ISSUE THREAD

**Issue by dstpierre** [staticbackendhq/core#56]
There's missing functions from a server-side function PoV from the `internal.Volatilizer` (Cache / PubSub) interface that would be useful  to have in functions.

The custom server-side runtime is implemented in the `function` package in the `runtime.go` file.

At this moment the runtime adds functions that are made available from the function's JavaScript interpreter.

In the function `addVolatileFunctions` in `runtime.go` line:391 we would need to add the following functions from the interface.

*Look at the `send` function for an example*

`cacheGet` and `cacheSet` would wrap the interface's `GetType` and `SetType` functions which will handle passing `string` as well as any object.

`inc` and `dec` would map to the interface's `Inc` and `Dec` functions

Lastly `queueWork` maps to the interface's `QueueWork` function

Adding those runtime functions will enable a world of possibility from server-side function, even though they run inside a sandboxed runtime.

**Comment by Baibhab97** [comment]
Hi, please let me know, if this issue is still open; I would like to contribute on it.

**Comment by dstpierre** [comment]
@Baibhab97 sure, I've assigned the issue to you. Please do not hesitate if you have any questions or want to validate anything. 

Thanks for your interests and contribution.

**Comment by g41797** [comment]
see #84 with similar functionality

**Comment by dstpierre** [comment]
Hey @Baibhab97 checking how things are going with this issue? The v1.5 is about to launch and I'd like to squeeze that one in.

Have you started something yet? Maybe I can help with the implementation if you create a PR.

**Comment by Baibhab97** [comment]
Hi @dstpierre, due to some other time commitments, I couldn't look into it. And for the next few days also, I would not be able to look into the same. You can unassign this from me. Apologies for the inconvenience.

**Comment by g41797** [comment]
Hi @dstpierre, as far as i understand this functionality similar to #84
if "yes" - i can take it 
there is one problem - i have no clue how to sync my main branch
(second branch updated without problem)

**Comment by dstpierre** [comment]
@Baibhab97 no worries at all and thanks for the update.

**Comment by dstpierre** [comment]
Thanks @g41797 - yes it's similar to that one. But as I'm wrapping the v1.5 release (ideally tomorrow), I'll keep this one.

As for your sync question, do you mean having your `main` branch of your fork updating from upstream main? Check this article it might help: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
