### ISSUE TITLE
Add Count functions in database

### ISSUE THREAD

**Issue by dstpierre** [staticbackendhq/core#60]
Sometimes, it's useful to have a count of how many records there is in a collection with or without filters.

Adding a `Count` functions in all 3 `database` engine supported would involves the following:

1. Adding the function in the `Persister` interface in the `database` package
2. Implement it for the `postgresql`, `mongo`, and `memory` database engine
3. Add an endpoint in the backend API

Depending if you write your tests first or not, but having a tests in the main package as well as inside the different db engine ones would be nice.

Since the return type would be `int64, error` there's no need to implement a generic function in the `backend`'s `Database[T]` functions set.

I'd see the following function prototype:

```go
// Count returns the numbers of entries in a collection based on optional filters
Count(auth model.Auth, dbName, col string, filters map[string]interface{})` (int64, error)
```

The `filters` would be optional. See how the `UpdateMany` function also uses similar `filters`

For the endpoint, we could have a new route in `server.go` around the routes starting with `/db` and have a new one like `/db/count/` which would call an handler defined in `db.go` that would accept POST request with the optional filters (look in `db.go` for example of the UpdateMany).

*p.s. the typical database security apply, so the standard permission checks would happen before the optional filters*

**Comment by VladPetriv** [comment]
Can u assign it for me? @dstpierre

**Comment by VladPetriv** [comment]
How we'll get column name? From url like `/db/count/{{column_name}}`?🤔

**Comment by dstpierre** [comment]
@VladPetriv there's no need to `column_name`. It's a count for the entire collection optionally based on filters (like the Query and the UpdateMany).

It counts the numbers of rows matching the filters, or without filters. It's an HTTP that's made to `/db/count` which accept a similar filters as the query function or no filter.

Hope that helps clarify. Let me know.

**Comment by VladPetriv** [comment]
✅Got it.  But from where you want to get collection name?🤔

**Comment by dstpierre** [comment]
ho yep now I get you :+1: , it'd say from the URL. `/db/count/` a real URL will look like this:

`/db/count/tasks` where tasks is the collection name. You grab it via the `getURLPath(path, 3)` for instance. Do not use the soon deprecated `ShiftPath` function as of #62

**Comment by VladPetriv** [comment]
Also have a question about this
``` go
field = fmt.Sprintf(`data->>'%s'`, field)
```
What does `data->>` mean? Because in my case `PosgreSQL` returns this error `pq: column "data" does not exist` but if I remove this `data->>` it works fine

**Comment by dstpierre** [comment]
this is how PG wants the field name to be when querying on a field. the `data` field is a JSONB and the syntax ``data->>'field-name' is the way to target a field name from the JSONB object.

Not sure why you're getting an error though. Technically you would not need this for the Count though, you'd use the same function to build the filters as the `QueryDocument` or the `UpdateMany` functions for instance.

Also the `data` field is only present on user's defined collection, not built-in SB collection, for example the `sb_accounts` has no `data` JSONB field, but is a real PG table without JSON data.

**Comment by VladPetriv** [comment]
@dstpierre  Can you review my PR?
