### ISSUE TITLE
[refactor]: Remove ShiftPath and replace with getURLPart

### ISSUE THREAD

**Issue by dstpierre** [staticbackendhq/core#62]
For simplicity the `ShiftPath` should be removed and all its usage should be replace with the `getURLPart`.

`ShiftPath` is takiing the request path and return the last value of the URL and return a modified shrinked version:

```go
// URL: /a/b/c
r.URL.Path, c := ShiftPath(r.URL.Path) // c = "c"
r.URL.Path, b := ShiftPath(r.URL.Path) // b = "b"
```

The simpler `getURLPart` function gets an URL value by index:

```go
// URL: /a/b/c
c := getURLPart(r.URL.Path, 3) // notice that indexes starts at 1, not 0. a is at idx 1, b at 2 and c at 3
```

I'd start this refactor by removing the `ShiftPath` function from `url.go`. In fact, I'd delete the entire `url.go` file and `go build` to fix compile error.

Before replacing a call to `ShiftPath` we need to make sure we know the proper index we want to use with the `getURLPart`.

For this, reverting to the URL in `server.go` for this handler would be how I'd ensure.

**Comment by VladPetriv** [comment]
Please change `getURLPath` to `getURLPart`

**Comment by dstpierre** [comment]
@VladPetriv thanks for the heads-up, what a typo I did there :wave:

**Comment by VladPetriv** [comment]
@dstpierre Can you review my PR?
