### ISSUE TITLE
Add email interface to server-side function runtime

### ISSUE THREAD

**Issue by dstpierre** [staticbackendhq/core#84]
We need to add the ability to send email from server-side function.

In the `runtime.go` file of package `function` we could add the `Emailer`:

* We could add the `Emailer` interface in the `ExecutionEnvironment` at line:20.
* We would need to pass the implementation when calling the `Execute` function.
* We would need to expose an `email()`  function to the function runtime, for instance at line:114 in the `addHelpers` function, we could expose the `email` function accepting what needs to satify the `Send` function of `Emailer`.

**Comment by g41797** [comment]
Hi
- Is it urgent issue?
- Is functions_test.go suitable for the testing?
- What is your dev environment?

Thanks
@g41797

**Comment by dstpierre** [comment]
Hey @g41797 my answers:

> Is it urgent issue?
No, I'm planning on releasing v1.5 in the following weeks, but this can be released later, say v1.5.1*

> Is functions_test.go suitable for the testing?
Yes, you could either add your call to the `sendEmail` helper function in the existing function test or create a new one, it's up to you. While testing the `dev` EmailProvider is used, so it will print out the content of the email to the console. I suggest running `make test-core` or `go test` to see this output while testing.

> What is your dev environment?
I've created a video here. Lately I've been using GitHub Codespaces sometimes which includes a PostgreSQL, MongoDB and Redis inside a Docker. When I ran Linux I had those locally, but now I had to run on Windows for accessibility reasons, and WSL2 and Docker are not the best match (for me at least). I tried Podman, which sometimes works and sometimes not.

I've recently implemented a `SQLite` data provider as well removing the need to have any other services installed, coupled with the memory Redis, it's easier to just git clone and start implementing.

Basically your steps are:

1. `git clone git@github.com:staticbackendhq/core.git`
2. Copy the .demo.env to .env -> `cp .demo.env .env`
3. Edit `.env` to use your choice  of database / redis

If you're going to use the PostgreSQL or Mongo setting, change the host to localhost if you're using Docker. Same for Redis

As an example, here's what I'm currently using which uses SQLite and a memory mplementation instead of Redis:

```
APP_ENV=dev

APP_SECRET=a-very-long-key-should-be-32long

APP_URL=http://localhost:8099

# For PostgreSQL
#DATABASE_URL=host=localhost user=postgres password=postgres dbname=postgres sslmode=disable
#DATA_STORE=pg

# For MongoDB
# DATABASE_URL=mongodb://localhost:27017
# DATA_STORE=mongo

# For SQLite
DATABASE_URL=dev.db
DATA_STORE=sqlite

JWT_SECRET=changeMe
MAIL_PROVIDER=dev
STORAGE_PROVIDER=local
FROM_EMAIL=you@domain.com
FROM_NAME=Your company
# REDIS_HOST=localhost:6379
REDIS_HOST=mem
REDIS_PASSWORD=
LOCAL_STORAGE_URL=http://localhost:8099
```
Once you have this file created you should be able to run `make test-core` as well as start the server with `make start`

Please look inside the `Makefile` if you're not using `make` to get those commands.

Hope that helps and let me know if you'd want me to assign this issue to you.

**Comment by dstpierre** [comment]
Hey, I merged #91 which I believe will fixed the issue regarding the pubsub connection (adding the "mem" in the REDIS_HOST was good, but there was still an issue in the `backend.Setup` should be better now.

I'd do a `git pull origin main` and merge into your branch and retry the `make test-core` and the `make start`

Let me know how it goes.

**Comment by dstpierre** [comment]
Alos @g41797 I'm getting intermitant error for the `sqlite` implementation and running the test, error is "DATABASE IS BUSY".

For  stability you might want to use either PostgreSQL or Mongo. The SQLite isn't released yet and seems to generates randon issues.

**Comment by g41797** [comment]
me2:
membership_test.go:63: HTTP Status:500 Internal Server Error Error:database is locked (5) (SQLITE_BUSY)

**Comment by g41797** [comment]
how i can simultaneously start dbs under docker and tests under vscode?

**Comment by dstpierre** [comment]
The `.demo.env` has `host=db due to the name in the `docker-compose-demo.yml`

This part is certainly confusing, I'll try to clarify this in the CONTRIBUTING.md no worries.

And yes, since `make test-core` passes, you're all set now.

**Comment by g41797** [comment]
I'd like to understand the task

    http.Handle("/sudo/sendmail", middleware.Chain(http.HandlerFunc(sudoSendMail), stdRoot...))

   [client]backend.SendMai ==> POST ..."/sudo/sendmail"... =>  [serversudoSendMail] ==> backend.Emailer.Send...

So send mail already exists for the client

"...ability to send email from **server-side function**"  - ExecData

OK i got the point:
- Server-side function is JS code dynamically uploaded to backend
- JS code has possibility to call go functions registered in  ExecutionEnvironment

**Comment by dstpierre** [comment]
Yes, exactly, this issue is for adding a `sendEmail` function to the VM (~virtual machine) or runtime the server-side JavaScript function run into.

Server-side functions are not fully fledge JavaScript runtime, for instance, developers cannot import JavaScript library and so on, it's using JavaScript as a dynamic language to perform tasks that would have been not safe to do on the client-side code.

The `ExecutionEnvironment` exposes internal Go code to this runtime environment and allow the runtime to make those services available via functions callable from inside the runtime.

Example for the email function 

```go
err = vm.Set("sendMail", func(call goja.FunctionCall) goja.Value {
  //...
})
```
In the `ExecutionEnvironment` type you'll have to add the `Emailer` interface:

```go
type ExecutionEnvironment struct {
  //...
  Volatile  cache.Volatilizer
  Email     email.Emailer
   //...
}
```
You can check the `fetch` function for inspiration on how to receive your parameters, because an object would be better than listing all required argument.

The `email.SendMailData` is what the `Send` method from the `Emailer` interface wants, so your runtime function could also accept this, for instance from a calling point-of-view:

```js
// this is an example of how your helper function would be call inside a server-side- function
function handle() {
  sendMail({
    from: "me@backend.com",
    to: "user1@domain.com",
    subject: "Your trial has expired",
    htmlBody: "<h1>Hello</h1>...",
    textBody: "Hello\n\n...",
  });
}
```
Something like that, you helper runtime function basically needs to do this:

1. Parse the input (refer to the `fetch` example for a very similar one.
2. Call the ` vm.Email.Send()` with the struc you've parsed in 1

To test, the quickest way like we said is to add a `sendMail` call in the `functions_test.go` and use the `make test-core` which you should see the output of the dev Emailer impl which prints to the console.

Let me know how it goes.

**Comment by g41797** [comment]
1.
"...at line:114 in the addHelpers function, we could expose the email function..."
It means to use HTTP request for send mail. What's the reason?

2.

	_, err = handler(goja.Undefined(), args...)
	go env.complete(err)
	if err != nil {
		return fmt.Errorf("error executing your function: %v", err)
	}

Looks check of err is obsolete

**Comment by dstpierre** [comment]
#95 is merged, thank you.
